version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  nodeosd:
    build:
      context: .
    image: eosio/eos
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - enunode-data-volume:/opt/eosio/bin/data-dir

  enuwallet:
    image: eosio/eos
    command: /opt/eosio/bin/enuwallet --wallet-dir /opt/eosio/bin/data-dir
    hostname: enuwallet
    links:
      - nodeosd
    volumes:
      - enuwallet-data-volume:/opt/eosio/bin/data-dir

volumes:
  enunode-data-volume:
    external: true
  enuwallet-data-volume:
    external: true
