version: "3"

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data-volume:/data/db

  nodeosd:
    image: enumivo/eos:latest
    command: /opt/enumivo/bin/nodeosd.sh --data-dir /opt/enumivo/bin/data-dir --resync --mongodb-uri mongodb://mongo:27017/ENU
    hostname: nodeosd
    links:
      - mongo
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - enunode-data-volume:/opt/enumivo/bin/data-dir

  enuwallet:
    image: enumivo/eos:latest
    command: /opt/enumivo/bin/enuwallet --wallet-dir /opt/enumivo/bin/data-dir
    hostname: enuwallet
    links:
      - nodeosd
    volumes:
      - enuwallet-data-volume:/opt/enumivo/bin/data-dir

volumes:
 mongo-data-volume:
   external: true
 enunode-data-volume:
   external: true
 enuwallet-data-volume:
   external: true